# Generated by Django 5.1.5 on 2026-02-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Doctor's fee", max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount in ₹', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount % applied', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='medicine_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of medicines', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax on medicines', max_digits=10),
        ),
    ]
