# Generated by Django 5.1.5 on 2026-02-25 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicines_json',
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('dosage', models.CharField(help_text='e.g. 500mg', max_length=100)),
                ('frequency', models.CharField(help_text='e.g. Twice daily', max_length=100)),
                ('duration_days', models.PositiveIntegerField(default=7, help_text='Number of days')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of prescription', max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, help_text='Tax % at time of prescription', max_digits=5)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='medicines.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
