# Generated by Django 5.1.5 on 2026-02-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('OINTMENT', 'Ointment'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('SURGICAL', 'Surgical Item'), ('LAB_TEST', 'Lab Test'), ('OTHER', 'Other')], default='TABLET', max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Unit price in ₹', max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=12.0, help_text='GST/tax percentage', max_digits=5)),
                ('requires_prescription', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Global discount percentage applied to all invoices', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
